### ISSUE TITLE
java.lang.ClassNotFoundException: Didn't find class "expo.modules.adapters.react.PromiseWrapper"

### ISSUE THREAD

**Issue by Gitveu** [hax0r31337/SteamGuardExtractor#2]
[ 2024-11-04T23:22:22.565    10268: 25343: 25343 I/LSPosed-Bridge  ] Loading legacy module dev.sora.extractor from /data/app/~~W1xS-PVNgoceNB-6sLhDVQ==/dev.sora.extractor-6_4djslJt1APolnOP72_6w==/base.apk
[ 2024-11-04T23:22:22.570    10268: 25343: 25343 I/LSPosed-Bridge  ]   Loading class dev.sora.extractor.XposedInit
[ 2024-11-04T23:22:22.702    10268: 25343: 25343 E/LSPosed-Bridge  ] java.lang.ClassNotFoundException: Didn't find class "expo.modules.adapters.react.PromiseWrapper" on path: DexPathList[[zip file "/data/app/~~Hok8a4furnRFSbfM5NEVEw==/com.valvesoftware.android.steam.community-e6Rd51nSZZoeHztymTMhwA==/base.apk"],nativeLibraryDirectories=[/data/app/~~Hok8a4furnRFSbfM5NEVEw==/com.valvesoftware.android.steam.community-e6Rd51nSZZoeHztymTMhwA==/lib/arm64, /data/app/~~Hok8a4furnRFSbfM5NEVEw==/com.valvesoftware.android.steam.community-e6Rd51nSZZoeHztymTMhwA==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:637)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:573)
	at dev.sora.extractor.XposedInit.handleLoadPackage(Unknown Source:66)
	at K.cvy.SVvopchujzLHEhws.IXposedHookLoadPackage$Wrapper.handleLoadPackage(Unknown Source:2)
	at K.cvy.SVvopchujzLHEhws.callbacks.XC_LoadPackage.call(Unknown Source:6)
	at K.cvy.SVvopchujzLHEhws.callbacks.XCallback.callAll(Unknown Source:26)
	at C0.b(Unknown Source:285)
	at java.lang.reflect.Method.invoke(Native Method)
	at org.lsposed.lspd.impl.LSPosedBridge$NativeHooker.callback(Unknown Source:240)
	at LSPHooker_.createOrUpdateClassLoaderLocked(Unknown Source:11)
	at android.app.LoadedApk.getClassLoader(LoadedApk.java:1126)
	at android.app.LoadedApk.getResources(LoadedApk.java:1374)
	at android.app.ContextImpl.createAppContext(ContextImpl.java:3324)
	at android.app.ContextImpl.createAppContext(ContextImpl.java:3316)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6879)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2236)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8177)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
[ 2024-11-04T23:23:51.800    10268: 25652: 25652 I/LSPosed-Bridge  ] Loading legacy module dev.sora.extractor from /data/app/~~W1xS-PVNgoceNB-6sLhDVQ==/dev.sora.extractor-6_4djslJt1APolnOP72_6w==/base.apk
[ 2024-11-04T23:23:51.802    10268: 25652: 25652 I/LSPosed-Bridge  ]   Loading class dev.sora.extractor.XposedInit
[ 2024-11-04T23:23:51.873    10268: 25652: 25652 E/LSPosed-Bridge  ] java.lang.ClassNotFoundException: Didn't find class "expo.modules.adapters.react.PromiseWrapper" on path: DexPathList[[zip file "/data/app/~~Hok8a4furnRFSbfM5NEVEw==/com.valvesoftware.android.steam.community-e6Rd51nSZZoeHztymTMhwA==/base.apk"],nativeLibraryDirectories=[/data/app/~~Hok8a4furnRFSbfM5NEVEw==/com.valvesoftware.android.steam.community-e6Rd51nSZZoeHztymTMhwA==/lib/arm64, /data/app/~~Hok8a4furnRFSbfM5NEVEw==/com.valvesoftware.android.steam.community-e6Rd51nSZZoeHztymTMhwA==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:637)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:573)
	at dev.sora.extractor.XposedInit.handleLoadPackage(Unknown Source:66)
	at K.cvy.SVvopchujzLHEhws.IXposedHookLoadPackage$Wrapper.handleLoadPackage(Unknown Source:2)
	at K.cvy.SVvopchujzLHEhws.callbacks.XC_LoadPackage.call(Unknown Source:6)
	at K.cvy.SVvopchujzLHEhws.callbacks.XCallback.callAll(Unknown Source:26)
	at C0.b(Unknown Source:285)
	at java.lang.reflect.Method.invoke(Native Method)
	at org.lsposed.lspd.impl.LSPosedBridge$NativeHooker.callback(Unknown Source:240)
	at LSPHooker_.createOrUpdateClassLoaderLocked(Unknown Source:11)
	at android.app.LoadedApk.getClassLoader(LoadedApk.java:1126)
	at android.app.LoadedApk.getResources(LoadedApk.java:1374)
	at android.app.ContextImpl.createAppContext(ContextImpl.java:3324)
	at android.app.ContextImpl.createAppContext(ContextImpl.java:3316)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6879)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2236)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8177)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
[ 2024-11-04T23:24:25.620    10076: 25944: 25944 I/LSPosed-Bridge  ] Loading legacy module com.github.dan.NoStorageRestrict from /data/app/~~ZJ7VXnTHekzbHJISbENpNw==/

**Comment by NightMean** [comment]
See #1 for alternative app
